### PR TITLE
fsyncsnoop: a new tool to trace fsync() system call

### PR DESCRIPTION
**Pull request by yangoliver**
While investigating some fsync performance issues, I wrote this
tool. The implemetation was learned from opensnoop.

This script needs lsof support to map fd to a file path.

Signed-off-by: Oliver Yang <yangoliver@gmail.com>

### CODE REVIEW

**Comment by brendangregg** [comment]
G'Day,

Thanks, tracing fsync latency with PID and pathname should be useful.

There's a couple of major problems, and some minor ones here. These are either with the code or the problem space in general.

Major:

1. I'm most worried about the overhead of calling an external program, lsof, for every line of output. I've debugged multiple lsof overhead issues in the past, where a sysadmin has automated its use too much (eg, see examples/execsnoop_example.txt). The problem here would be if an application calls fsync() frequently. Eg, can a database fsync() every log write, causing thousands of fsyncs per second? If so, this tool will eat a CPU, and could cause performance issues of its own.

Ideally, the tracepoint gives us the pathname directly in its format string. Next best would be a pointer to a kernel struct and we'd walk there (although that may involve unstable implementation details, making it less suitable). Since the tracepoint only gives us the FD number, we're a bit stuck.

I'd look at reading it from /proc/PID/fd. Without calling an external program, like "ls -l".

If the overhead of reading the fd->pathname mapping is still a bit much, I'd also look at caching it (PID, fd -> pathname) and using it from the cache rather than redoing the map lookup. Since we have timestamps, I'd also expire it from the cache if it's more than 100 milliseconds old. That should ensure a database calling fsync() frequently on a log file would at most do 10 map lookups per second, and the rest come from the cache. Anyway. Only if the map looking remains somewhat expensive.

2. There's a race condition between fsync() and the map lookup (lsof, or whatever).

I wrote a simple program to test fsync(), below, and found that fsyncsnoop often identified the wrong path. I was writing and saving the program using vim, which also calls fsync().

```C
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char *argv[])
{
        char buf[1024];
        const char *outfile = "out";
        int fd;

        if ((fd = open(outfile, O_CREAT|O_WRONLY|O_TRUNC, 0644)) < 0) {
                printf("ERROR opening out file. Exiting.\n");
                exit(1);
        }
        write(fd, &buf, 1024);
        // sleep(1);
        fsync(fd);
        close(fd);

        return (0);
}
```

If I include the sleep(1), it works.

How do we handle the race? If the race can't be fixed, the documentation needs to make it clear this may happen.

There's some ways to help or fix it, with their own pros and cons, such as also tracing open() and close(). The cons is that this adds more overhead, and perhaps brittleness. Perhaps a compromise is to only trace close(), so that -- by comparing timestamps -- we can at least identify if a FD has expired by the time we try to do the mapping, and just print "<closed>".

Minor:

- no man page
- no examples file
- no /bin symlink
- Should it handle other sync types? fsyncdata? No is fine, if clearly documented what it does and doesn't trace.
- block comment out of date (mentions tracing getname(), etc)
- last line of comment (date, author, created this) needs changing; either change to you created this, or add a line to say you repurposed this.
- copyright line: you could optionally append another line with your own copyright, if you are interested.

**Comment by yangoliver** [comment]
Gregg,

Thanks for your detailed comments. Please see my replies begin with
"Oliver>".

2015-01-20 5:46 GMT+08:00 Brendan Gregg <notifications@github.com>:

> G'Day,
>
> Thanks, tracing fsync latency with PID and pathname should be useful.
>
> There's a couple of major problems, and some minor ones here. These are
> either with the code or the problem space in general.
>
> Major:
>
>    1. I'm most worried about the overhead of calling an external program,
>    lsof, for every line of output. I've debugged multiple lsof overhead issues
>    in the past, where a sysadmin has automated its use too much (eg, see
>    examples/execsnoop_example.txt). The problem here would be if an
>    application calls fsync() frequently. Eg, can a database fsync() every log
>    write, causing thousands of fsyncs per second? If so, this tool will eat a
>    CPU, and could cause performance issues of its own.
>
> Ideally, the tracepoint gives us the pathname directly in its format
> string. Next best would be a pointer to a kernel struct and we'd walk there
> (although that may involve unstable implementation details, making it less
> suitable). Since the tracepoint only gives us the FD number, we're a bit
> stuck.
>
> I'd look at reading it from /proc/PID/fd. Without calling an external
> program, like "ls -l".
>
Oliver> Thanks for sharing the experiences here.

> If the overhead of reading the fd->pathname mapping is still a bit much,
> I'd also look at caching it (PID, fd -> pathname) and using it from the
> cache rather than redoing the map lookup. Since we have timestamps, I'd
> also expire it from the cache if it's more than 100 milliseconds old. That
> should ensure a database calling fsync() frequently on a log file would at
> most do 10 map lookups per second, and the rest come from the cache.
> Anyway. Only if the map looking remains somewhat expensive.
>
Oliver>I considered that before.

           The fd to a full path name by kernel data structure walking is
not easy.

           In the context of fsync, we just can get struct file, which has
the member of f_path.
           In f_path, we can get dentry.

           In dentry, we just can get a file name. For full path name, we
need walk all dentry's parents.

Below is my crash dump tools debug output for your reference,

crash> dentry 0xffff883fbc74f468
struct dentry {
  d_flags = 192,
  d_seq = {
    sequence = 4
  },
  d_hash = {
    next = 0x0,
    pprev = 0xffffc90006c2a6f8
  },
  d_parent = 0xffff883fb52d1788, >>>>>>> Need walk parent
  d_name = {
    hash = 25951299,
    len = 4,
    name = 0xffff883fbc74f4a0 "cron" >>>>>>>> fd's name is here
  },


For reading /proc/PID/fd, did you mean using external shell assistance?
I think it is better than lsof from overhead perspective. But it may have a
same race condition issue.

>
>    1. There's a race condition between fsync() and the map lookup (lsof,
>    or whatever).
>
> I wrote a simple program to test fsync(), below, and found that fsyncsnoop
> often identified the wrong path. I was writing and saving the program using
> vim, which also calls fsync().
>
> #include <unistd.h>
> #include <sys/types.h>
> #include <sys/stat.h>
> #include <fcntl.h>
> #include <stdio.h>
> #include <stdlib.h>
> intmain(int argc, char *argv[])
> {
>         char buf[1024];
>         const char *outfile = "out";
>         int fd;
>
>         if ((fd = open(outfile, O_CREAT|O_WRONLY|O_TRUNC, 0644)) < 0) {
>                 printf("ERROR opening out file. Exiting.\n");
>                 exit(1);
>         }
>         write(fd, &buf, 1024);
>         // sleep(1);
>         fsync(fd);
>         close(fd);
>
>         return (0);
> }
>
> If I include the sleep(1), it works.
>
> How do we handle the race? If the race can't be fixed, the documentation
> needs to make it clear this may happen.
>
Oliver> Thanks for pointing it out. I did learn sth here. :)

             Maybe we should use kprobe to walk kernel data structure
instead of using external tools.

             In fsync context, kprobe may walk the data structure.

             I think kprobe may still introduce some overheads, but it is
better than a wrong file name.

> There's some ways to help or fix it, with their own pros and cons, such as
> also tracing open() and close(). The cons is that this adds more overhead,
> and perhaps brittleness. Perhaps a compromise is to only trace close(), so
> that -- by comparing timestamps -- we can at least identify if a FD has
> expired by the time we try to do the mapping, and just print "".
>
Oliver> Before using lsof, I used to have another implementation by using
open.

             The problem there was. If the process are daemon, you can't
have open/close calls in the context. So most of daemon's files will not
have the filename.

             That is why I use lsof in new implementation.


> Minor:
>
>    - no man page
>    - no examples file
>    - no /bin symlink
>    - Should it handle other sync types? fsyncdata? No is fine, if clearly
>    documented what it does and doesn't trace.
>    - block comment out of date (mentions tracing getname(), etc)
>    - last line of comment (date, author, created this) needs changing;
>    either change to you created this, or add a line to say you repurposed this.
>    - copyright line: you could optionally append another line with your
>    own copyright, if you are interested.
>
> Thanks for giving me the guidelines to integrate a new tool.

If I can address the major problems, I'd like to follow your process.


-- 
------------------
Oliver Yang

**Comment by yangoliver** [comment]
Gregg,

I think I misunderstood the second major issue you mentioned below.
See my updates below.

2015-01-20 8:35 GMT+08:00 oliver yang <yangoliver@gmail.com>:


> For reading /proc/PID/fd, did you mean using external shell assistance?
> I think it is better than lsof from overhead perspective. But it may have a
> same race condition issue.

Oliver> I noticed that you already mentioned without using "ls -l".
            Please let me know if you already have the specific methods.

            Today, I will try kprobe to walk the kernel data structure.
            But I'm not quite sure whether ftrace support complex
kprobe instruments for walking data structure. I'm newbie in ftrace
and kprobe.

>>
>> There's a race condition between fsync() and the map lookup (lsof, or
>> whatever).
>>
>> I wrote a simple program to test fsync(), below, and found that fsyncsnoop
>> often identified the wrong path. I was writing and saving the program using
>> vim, which also calls fsync().
>>
>> #include <unistd.h>
>> #include <sys/types.h>
>> #include <sys/stat.h>
>> #include <fcntl.h>
>> #include <stdio.h>
>> #include <stdlib.h>
>>
>> int
>> main(int argc, char *argv[])
>> {
>>         char buf[1024];
>>         const char *outfile = "out";
>>         int fd;
>>
>>         if ((fd = open(outfile, O_CREAT|O_WRONLY|O_TRUNC, 0644)) < 0) {
>>                 printf("ERROR opening out file. Exiting.\n");
>>                 exit(1);
>>         }
>>         write(fd, &buf, 1024);
>>         // sleep(1);
>>         fsync(fd);
>>         close(fd);
>>
>>         return (0);
>> }
>>
>> If I include the sleep(1), it works.
>>
>> How do we handle the race? If the race can't be fixed, the documentation
>> needs to make it clear this may happen.
>
> Oliver> Thanks for pointing it out. I did learn sth here. :)
>
>              Maybe we should use kprobe to walk kernel data structure
> instead of using external tools.
>
>              In fsync context, kprobe may walk the data structure.
>
>              I think kprobe may still introduce some overheads, but it is
> better than a wrong file name.
>>
>> There's some ways to help or fix it, with their own pros and cons, such as
>> also tracing open() and close(). The cons is that this adds more overhead,
>> and perhaps brittleness. Perhaps a compromise is to only trace close(), so
>> that -- by comparing timestamps -- we can at least identify if a FD has
>> expired by the time we try to do the mapping, and just print "".
>
> Oliver> Before using lsof, I used to have another implementation by using
> open.
>
>              The problem there was. If the process are daemon, you can't
> have open/close calls in the context. So most of daemon's files will not
> have the filename.
>
>              That is why I use lsof in new implementation.
>

I misunderstood the race condition you mentioned here.

Yes. A local cache for [pid, fd,pathname] should work.

In my earlier implementation, I use your opensnoop code to get the
pathname, and fetch the pathname from local array.

I will find some time to try a better solution today.

**Comment by yangoliver** [comment]
Some thoughts about two major issues.

Goals: 1) avoid external shell command fork/exec overheads
            2) How to correlate fsync enter fsync exit, open, close trace results correctly
                If we used array cache in awk, how to limit the resource consumption.

Option a: Using ftrace kprobe events to get the file name.

                fsync code path will call into dput, then we can set kprobe event for dput entry point.
                dentry->d_name should be the file name.

                Issue 1: I'm not familiar with kprobe syntax to fetch a non-zero offset of struct member.
                              Need check Linux documents
                Issue 2: dentry->d_name is not full path name. ftrace kprobe event seemed not to support to
                              walk the data structure 
                Iusse 3: Depends on kernel implementation. dput code might get changed.

Option b: Using open/getname to get the filename. Using awk array to cache and match filename to a
                fd with fsync operation. 
              
                Issue 1: If daemons don't call open, then we don't have the opportunities to get file name.
                Issue 2: Need control awk array cache size. 
                             Maybe need ring buffer implementation in awk?

Option c:  use anther sort of language to do "readlink /proc/<pid>/fd/<fd>" without fork/exec ops.
                I'm not familiar with script language, but maybe other language could use native system call
                to get the symbol link of proc file.

                Issue 1:  As ftrace output and readlink system call could race, how can we know the result is
                              correct or not. It is possible get the wrong results.

Option d: Hybrid way?

               Leverage kprobe to get the filename, but the case of can't get filename, just using readlink
               system call to get a best guess.
 
               In snoop tool output, we can mark the guessing results and correct results differently.

**Comment by yangoliver** [comment]
I got confused about race condition.

In my original script, I had the assumption that fsync enter and exit syscall output should not be inserted by other process fsync trace results.

If we have process A and B calls fsync at same time, can ftrace code cause below issue?

    fsync_enter for A
    fsync_enter for B
    fsync_exit for A
    fsync_exit for B

I think ftrace should always ensure that syscal enter and exit output belong to a same process are outputed together with the right order.

If ftrace couldn't ensure that, I think it would be ftrace bug.

Do you agree that?

For the bug found by your testing, I suspected that it was caused by my below script.

		if (has_lsof) {
			cmd = "lsof -a -F n -n -p" pid " -d " fd " | tail -n1"
			cmd | getline filename
                        >>>>>>>>>>>>>>>>>>>>> should add "close(cmd)" here
			sub(/^n/, "", filename)
		} else {
			filename = "N/A"
		}

**Comment by yangoliver** [comment]
I think my last comments about fsync order was not correct.

"In my original script, I had the assumption that fsync enter and exit syscall output should not be inserted by other process fsync trace results."

It looked like ftrace can't ensure multiple process fsync enter and exit outputs don't mixed together.
My 2nd version of check-in has no assumption about that order among multiple processes.

Currently the only assumption is enter and exit has the order for single process.

It seemed that it is quite difficult to solve fork/exec overhead by using external commands.
Maybe the right way is using other script language which support native readlink API.

I will continue to think about using kprobe to get the filename in kernel fsync code path.
I had several options,
  1.using  open/getname, but is that worth doing? 
     In my server, major fsync overheads caused by daemon, this way can't work if daemon already open the files.
  
  2. Use dentry in fsync kernel code path
       But dentry doesn't have full path.
       We don't want to depend on debug info. entry point kprobe functionality is limited.
       I also need learn how to fetch a c struct with a non-zero offset memeber.
       Another thing is, the implementation was bound to a very specific kernel version.

**Comment by brendangregg** [comment]
About multiple processes and concurrency: it can happen, and the various variables including time need to be keyed on the PID and FD number.

I took a look at bash: no readlink builtin :-(. It does have "finfo -l" in the source, which calls readlink, but that's a _loadable_ builtin.

On my Ubuntu 12.04 system, bash 4.2.25 doesn't have finfo, nor the source or binaries with the distribution. If I install the bash-builtins package, I get the source, but still no binaries.  If finfo was as simple as adding a package, that may be ok, but at this point it means both adding a package, then going and compiling up something (and needing a compiler).

Perl has readlink as a builtin. It's probably best to switch to perl instead of awk, for formatting and the builtin readlink.

open/getname won't work for already open files, as you mention. dentry might involve too high overheads anyway, for partial names.

If we think the race is still bad with perl readlink (it should get much better, without the fork/exec), then I'd just add tracing close(), so that we could note if an FD expired by the time we tried to readlink it.

Although... Perl has builtins for stat() and timestamps, and the symlinks are timestamped, so Perl may be able to determine if a /proc/PID/fd/* link has differed based on timestamps alone -- saving the need to trace close()!

**Comment by yangoliver** [comment]
Gregg,

Thanks for your detailed analysis.

Besides the perf, how about the python? Did you have personal script preferences for perf-tools.
You may define a long-term plan for this toolkit.

**Comment by brendangregg** [comment]
The plan for this toolkit is to come up with some temporary useful tools that serve in the interim until eBPF is available. Since they are temporary, basically sandcastles, I wouldn't put too much effort into them, as they will be rewritten later. I expect their lifespan will be about 2 years.

In this case, we need awk + a few extra functions: readlink(), and maybe stat() and time. I'd prefer Perl for that.

**Comment by yangoliver** [comment]
Thanks for sharing the roadmap.

Before your reply, I started the re-implementation by python.

Now the new commit re-implement all of original CLI options.

The readlink method is supported by python too. I think there is no fork overhead now. 

For stat() approach you mentioned above, I think it may not work.
In my testing, I found lots of daemon just keep fsync without closing the files.
For this reason, the stat() time returned may changed after that, but that doesn't mean the fd got reused by other file.

When guessing the filename, I also can give the "fd closed" messages to user, if the readlink can't return the successful value.

Below is the output in my 3.2 Linux. It tries to give all fsync operations longer than 30ms.

    ./fsyncsnoop -t 30
    Tracing fsync()s show latency longer than "30"ms. Ctrl-C to end.
    COMM             PID     LATms   FD RVAL FILE
    sysmon           450    38.08   36 0x0 socket:[1493780]
    syslogd          390    34.88    6 0x0 /ddr/var/log/debug/messages.engineering
    sysmon           450    32.67   36 0x0 /ddr/registry/p0/alerts_local.db3-journal
    sysmon           450    32.46   36 0x0 /ddr/registry/p0/alerts_local.db3-journal
    sysmon           450    32.86   36 0x0 /ddr/registry/p0/alerts_local.db3-journal
    dd_worker thr   26121  36.25   77 0x0 /ddr/registry/p0/config.db3-journal
    dd_worker thr   26121  37.23   77 0x0 /ddr/registry/p0/config.db3-journal
    syslogd          390    39.92    6 0x0 /ddr/var/log/debug/messages.engineering
    sysmon           450    30.53   36 0x0 ***the fd has closed[/proc/450/fd/36]

**Comment by yangoliver** [comment]
My new commit was incremental diff based on last awk script.
If you want a clean commit, I can use git rebase to recreate a single patch.

I had tested the tool on 3.2 based kernel. I will test it on latest kernel as well.

**Comment by yangoliver** [comment]
I used your program tested the new script on 3.12 kernel. It worked.
Depending on the timing, it could give the file name or just return fd closed messages.

Using close timestamp might work, but it will introduce the additional overhead for trace.
The tool is mainly used to trace the daemons instead of this kind of shot-term open-fsync-close application. Maybe in real work load, it is good enough.

The fstat() also has some problems,

a. The timestamp changes could be done by same process against same file. I observed this behaviors in our production evironment. In this case, even the file is touched before readlink, the filename is still valid.

b. The ftrace timestamp is CPU TSC, where as the fstat is different time value. We also need convert TSC to that time in the implementation.

Anyway, the ROI for getting filename seemed is not reasonable.

Let me know your opinions here. If you think current version is acceptable, I will do remaining work to meet perf-tools integration standards. Your comments are really helpful to me. I didn't learn a lot while working on this tool. 
 
Here is my ubuntu test results,

    $ sudo ./fsyncsnoop 
    Tracing fsync()s. Ctrl-C to end.
    COMM             PID     LATms   FD RVAL FILE
    a.out            6293     9.12    3 0x0 /home/oliver/work/perf-tools/file.txt
    a.out            6294     4.70    3 0x0 ***the fd has closed[/proc/6294/fd/3]
    a.out            6295     4.01    3 0x0 ***the fd has closed[/proc/6295/fd/3]
    a.out            6296     3.55    3 0x0 /home/oliver/work/perf-tools/file.txt
    a.out            6297     4.39    3 0x0 /home/oliver/work/perf-tools/file.txt
    a.out            6298     7.01    3 0x0 ***the fd has closed[/proc/6298/fd/3]
    a.out            6299     5.90    3 0x0 ***the fd has closed[/proc/6299/fd/3]
    a.out            6300     3.32    3 0x0 ***the fd has closed[/proc/6300/fd/3]
    a.out            6301     5.65    3 0x0 /home/oliver/work/perf-tools/file.txt
    a.out            6302     3.92    3 0x0 ***the fd has closed[/proc/6302/fd/3]
    a.out            6303     9.51    3 0x0 ***the fd has closed[/proc/6303/fd/3]
    a.out            6304     5.27    3 0x0 ***the fd has closed[/proc/6304/fd/3]
    a.out            6305     7.61    3 0x0 ***the fd has closed[/proc/6305/fd/3]
    a.out            6306     5.79    3 0x0 ***the fd has closed[/proc/6306/fd/3]
    ^C
    Ending tracing...
    $ uname -a
    Linux oliver-kern-dev 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brendangregg** [comment]
First time I tried in production:

{code}
[root@abcassandra--useast1e-i-e986f607 bgregg]# ./fsyncsnoop 
Tracing fsync()s. Ctrl-C to end.
COMM             PID     LATms   FD RVAL FILE
  File "<string>", line 58
    except OSError as e:
                    ^
SyntaxError: invalid syntax
^C
Ending tracing...
{code}

I took a look at the 3 timestamps (on /proc/PID/fd files), and the symlinks seem to be only created on /proc lookup, so the timestamps aren't helpful. I haven't thought of a better way to deal with that. The options are: 1) warn users about possible race in the _current_ implementation; 2) trace close(); 3) trace open() & close() (which I'd rather do later when we have eBPF).

**Comment by yangoliver** [comment]
Gregg,

What python version are you using?

I tested my script on different version of pyhton, can't replay your bug.

$ python -V
Python 2.7.6

I did a google search, it seemed there are some syntax changes between old python and latest python.

I submitted a new patch to change the exception syntax. Could you try it again?

If it still doesn't work, please let me know your python version. I will manage to install your version for testing.

**Comment by brendangregg** [comment]
That was python 2.4.3. The fix worked, so I now have production output.

Here's a database:

```
# ./fsyncsnoop 
Tracing fsync()s. Ctrl-C to end.
COMM             PID     LATms   FD RVAL FILE
multilog         4371    62.01    6 0x0 /service/platformservice/log/main/current
<...>            4813     0.72 3100 0x0 ***the fd has closed[/proc/4813/fd/3100]
<...>            4813     1.36 2479 0x0 ***the fd has closed[/proc/4813/fd/2479]
<...>            4813     0.00 3034 0x0 ***the fd has closed[/proc/4813/fd/3034]
<...>            4813    28.69 3035 0x0 ***the fd has closed[/proc/4813/fd/3035]
<...>            4813     0.00 3076 0x0 ***the fd has closed[/proc/4813/fd/3076]
<...>            4813     0.77 2479 0x0 ***the fd has closed[/proc/4813/fd/2479]
<...>            4813     0.00 3034 0x0 ***the fd has closed[/proc/4813/fd/3034]
<...>            4813     0.60 2479 0x0 ***the fd has closed[/proc/4813/fd/2479]
<...>            4813     0.00 3034 0x0 ***the fd has closed[/proc/4813/fd/3034]
^C
Ending tracing...
```

I'm a bit surprised by this; one of those fsync()s took 28 ms, and yet we still couldn't readlink quick enough, despite calling readlink on the entry to fsync() (instead of the exit). I'd assume the app didn't call close() until the fsync() completed, so this suggests that it takes longer than 28 ms from tracepoint to python calling readlink(), which is slower than I hoped.

Now an application (different server):

```
# ./fsyncsnoop 
Tracing fsync()s. Ctrl-C to end.
COMM             PID     LATms   FD RVAL FILE
multilog         2787     6.86    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     5.04    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     6.12    6 0x0 /service/postgres_agent/log/main/current
postdrop         6744    16.63    4 0x0 ***the fd has closed[/proc/6744/fd/4]
cleanup          6745    11.44   13 0x0 ***the fd has closed[/proc/6745/fd/13]
bounce           6748     5.45   13 0x0 ***the fd has closed[/proc/6748/fd/13]
cleanup          6745     5.51   13 0x0 ***the fd has closed[/proc/6745/fd/13]
bounce           6748     7.38   13 0x0 ***the fd has closed[/proc/6748/fd/13]
multilog         2787    14.46    6 0x0 /service/postgres_agent/log/main/current
<...>            2787    11.14    6 0x0 /service/postgres_agent/log/main/current
multilog         2787    12.69    6 0x0 /service/postgres_agent/log/main/current
multilog         2787    10.49    6 0x0 /service/postgres_agent/log/main/current
multilog         2785     3.72    6 0x0 /service/platformservice/log/main/current
multilog         2787    12.22    6 0x0 /service/postgres_agent/log/main/current
multilog         2787    31.91    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     5.90    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     5.78    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     7.10    6 0x0 /service/postgres_agent/log/main/current
multilog         2787     6.99    6 0x0 /service/postgres_agent/log/main/current
```

That's much better, although it's the database server I really care about. I think if someone else tried this, they'd file a bug to say the tool didn't work.

I've tried using nice(1), renice(1), and chrt(1) to increase the priority of fsyncsnoop so that it executes more quickly, without success. Eg: 

```
# nice -n -19 ./fsyncsnoop
Tracing fsync()s. Ctrl-C to end.
COMM             PID     LATms   FD RVAL FILE
vi               6149     2.18    6 0x0 /tmp/.zz.swp
vi               6149    40.12    5 0x0 ***the fd has closed[/proc/6149/fd/5]
vi               6149     2.64    6 0x0 /tmp/.zz.swp
vi               6149    44.18    5 0x0 ***the fd has closed[/proc/6149/fd/5]
vi               6149     2.23    6 0x0 /tmp/.zz.swp
vi               6149    37.70    5 0x0 /tmp/zz
vi               6149     2.94    6 0x0 /tmp/.zz.swp
vi               6149    37.40    5 0x0 ***the fd has closed[/proc/6149/fd/5]
```

I've also tried using stdbuf(1) to ensure the trace_pipe is flushed quickly.

If we could improve this so that only the very fast fsync()s reported "the fd has closed", eg, < 1ms, then that may be ok, since the tool should still serve its purpose: provide information on the _slow_ fsync()s. 

But we're far away from that: this is missing beyond 40 ms (and I've seen as high as 90 ms). Something is wrong -- I'm wondering what's going on in the kernel to take ftrace so long to pass out the event.

This also makes me worry more about false filenames. 40+ ms is a long time, and the fd could be reused by busy production apps. My example where it looks like the tool is behaving better, may in fact be worse -- it could be wrong data, instead of error messages.

FWIW, here's some strace, that matches the same type of fsyncsnoop output I showed earlier:

```
# strace -tt -T -e open,fsync,close -p 6149
Process 6149 attached
09:26:35.833916 --- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
09:26:35.845625 --- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
09:26:37.095630 fsync(6)                = 0 <0.002677>
09:26:37.098475 open("/tmp/zz", O_WRONLY|O_CREAT|O_TRUNC, 0644) = 5 <0.000682>
09:26:37.130329 fsync(5)                = 0 <0.044052>
09:26:37.174454 close(5)                = 0 <0.000050>
```

So the fsync() is followed by a close(). But it does take 44 ms, so I would have hoped we could processed trace_pipe and readlink in that timeframe.

I checked for any tunables for trace_pipe, in case there is a deliberate latency introduced (eg, for coalescing), but I haven't found anything yet. I did try reducing /sys/kernel/debug/tracing/buffer_size_kb, without success. There is a 100 ms timeout in poll_wait_pipe(), but I'm not sure that's related.

I've started wondering if this is pushing the current ftrace capabilities (pre-eBPF) too far.

If I had to do this currently, I may use funccount to get a handle on the rate of system calls for an application, and if they are slow enough, I could use strace(1) as shown earlier to get the info needed. (Note to anyone else reading: strace(1) will massively slow down ALL system calls, not just the ones filtered using -e, so you need to measure the rate of them ALL, not just open(), fsync(), and close(). strace(1) is really a debugging tool, not a performance tool). If funccount shows the rate of these is fast, the chances that we have an fsync() related issue are then less likely anyway.

I took a look at fanotify to see if it could do this, but it looks like it's missing a FAN_FSYNC style event.

SystemTap can do this (and should even be able to do FD->pathname lookups directly), but I'd like to see that work without debuginfo, which is a pain to have around on the cloud.

So, that's what I've been trying. I think the tool should work well enough, even if it had a < 1 ms race, but somehow we have a > 40 ms race, and that's a problem. I don't know why the race is so long.

**Comment by yangoliver** [comment]
Gregg,

Good testing. I should do more testing before submit the patch.
Sorry about that.

In order to rule out python problem, I tried to trace readlink performance in python,
The strace output showed that it is about 10+us.

    # strace -tt -T -e readlink -p 4187
    Process 4187 attached - interrupt to quit
    03:18:01.910853 readlink("/proc/390/fd/10", "/var/log/cron", 4096) = 13 <0.000014>
    03:18:21.807884 readlink("/proc/450/fd/36", "/ddr/registry/p0/alerts_local.db3-journal", 4096) = 41     <0.000014>
    03:18:21.909012 readlink("/proc/450/fd/37", 0x7fff433f6850, 4096) = -1 ENOENT (No such file or      directory) <0.000012>

I also add the tried to measure the whole time for each line process in while loop,

    (1422445808.086831, 1422445808.086853, 2.193450927734375e-05) >>> line of fsync enter, including readlink
    (1422445808.086897, 1422445808.086925, 2.8133392333984375e-05)>>>line of fsync exit
    sysmon           450      2.61   37 0x0 ***the fd has closed[/proc/450/fd/37]

You can see the fsync enter line just processed within 22us, including readlink.
And fsync took 2.61 ms, so the delay happened before the phython read lines from standard output.

There are two possibilities,

1.the huge delay happened ftrace. The ftrace code path buffered the log.
2.python buffered the input from stdin, which caused delay.

For issue 2, I already found it in my previous tesitng, and fixed it by using python -u option and sys.stdin.readline().

       -u     Force  stdin,  stdout  and  stderr  to  be totally unbuffered.  On systems where it matters, also put stdin, stdout and stderr in
              binary mode.  Note that there is internal buffering  in  xreadlines(),  readlines()  and  file-object  iterators  ("for  line  in
              sys.stdin")  which  is  not influenced by this option.  To work around this, you will want to use "sys.stdin.readline()" inside a
              "while 1:" loop.
  
Anyway, it looked like the issue was caused by ftrace.

**Comment by yangoliver** [comment]
I modified code to let python code read trace_pipe directly, and got follow output,

    1422450865.109396, 1422450865.109413, 0.000017
    1422450865.109420, 1422450865.109446, 0.000026
    <...>            13911   27.41    5 0x0 ***the fd has closed[/proc/13911/fd/5]

You can see, process fsync enter used 17us, but the fsync delay was 27.41ms.

So I really think the issue is related to ftrace implementation.

I use two scripts, one is original fsyncsnoop script, add sleep before cat trace_pipe.
Another is python script, which just copied python part into the script and add some timestamp debug.
 
Here is my python scripts:

    #!/usr/bin/python
    import sys
    import os
    import re
    import time
    from sys import argv

    #(script, offset, opt_name, name, opt_time, time_ms, opt_fail,
    #    opt_file, file) = argv

    #initializations
    #o = int(offset, 10)
    o=0
    opt_time=0
    opt_name=0
    opt_file=0
    if (opt_time == "1"):
        time_ms = float(time_ms)

    lastfd = {}
    lastname = {}
    lasttime = {}
    enter_flag = {}

    #free context
    def free_context():
        del lastname[pid, fd]
        del lasttime[pid, fd]
        del enter_flag[pid, fd]
        del lastfd[pid]

    f = open('/sys/kernel/debug/tracing/trace_pipe')
    #main loop
    while True:
        try:
    #        line = sys.stdin.readline()
            line = f.readline()
            t0 = time.time()
            if not line:
                break

            # common fields
            if (line.find("#") != 0):
                line = line.strip()
                keyidx = line.find("-")
                comm = line[0:keyidx]

                if (opt_name == "1" and comm.find(name) < 0):
                    continue

                subline = line[keyidx+1:len(line)]
                fields = subline.split()
                # Array indices start at 0 unlike AWK
                pid = fields[0]


            # sys_fsync() enter
            if (line.find("sys_fsync(fd:") > 0):
                fd = fields[4+o].replace(")", "")
                fd = int(fd,16)
                path = "/proc/%s/fd/%d"%(pid, fd)
                # guess the filename. It may not be correct as fd could
                # be closed and opened for another file.
                try:
                    filename = os.readlink(path)
                except OSError as e:
                    filename = "***the fd has closed[%s]"%path

                # save context
                lastfd[pid] = fd
                lastname[pid, fd] = filename
                lasttime[pid, fd] = float(fields[2+o].replace(":", ""))
                enter_flag[pid, fd] = 1

            # sys_fsync() exit
            if (line.find("sys_fsync ->") > 0):
                fd = lastfd[pid]
                filename = lastname[pid, fd]
                time_enter = lasttime[pid, fd]

                if (opt_file == "1"):
                    match = re.match(r".*"+file+".*", filename)
                    if not match:
                        free_context()
                        continue

                if enter_flag[pid, fd] == 1:
                    rval = fields[5+o]
                    time_exit = float(fields[2+o].replace(":", ""))
                    latency = (time_exit-time_enter)*1000
                    if (opt_time == "1" and latency < time_ms):
                        free_context()
                        continue
                    latency = "%.2f"%latency
                    print "%-16.16s %-6s %6s %4s %s %s"%(
                        comm, pid, latency, fd, rval, filename)

                    free_context()
                else:
                    print "WARNING: fsync exit without matched fsync enter"
                    print line

            # LOST event
            if re.match(r"LOST.*EVENTS", line):
                print "WARNING: Detect LOST EVENTs"
                print line

        t1 = time.time()
        print "%.6f, %.6f, %.6f"%(t0, t1, t1-t0)

        except KeyboardInterrupt as e:
            break

**Comment by yangoliver** [comment]
Close this pull request as there are some fundamental problems couldn't be addressed.

**Pull request closed without merging**
